### ISSUE TITLE
Вопрос по Bans & Comms

### ISSUE THREAD

**Issue by unqxl** [Flute-CMS/cms#20]
**Приветствую!**
У меня возник вопрос по поводу модуля `Bans & Comms`, точнее по части его визуала.
Ниже приложил фото проблемы, и суть её в том, что не все баны имеют заполненную колонку "Срок".
Тобиж где-то написано "Навсегда", а где-то пусто. Так и должно быть, или это визуальная ошибка?

![image](https://github.com/Flute-CMS/cms/assets/46648824/7261ef03-8b49-457a-b126-8a7128819370)

**Comment by unqxl** [comment]
Также присутствует такая проблема с полями ввода и кнопкой "Сохранить", полагаю.
Версия последняя стоит (0.2.1.3-alpha)

![image](https://github.com/Flute-CMS/cms/assets/46648824/40c219e2-d1ea-41a3-a60e-968244f05d9e)

**Comment by FlamesONE** [comment]
Все исправлено в новых версиях
