### ISSUE TITLE
Issues with games list when you add server

### ISSUE THREAD

**Issue by delmaff1** [Flute-CMS/cms#34]
There is a problem when adding the server and editing it! when you set another game CSGO/CS2 is automatically set, for example I uploaded 2 servers of cs 1.6 and gave a save, name information appears in the monitoring because they are automatically set by the platform on csgo/cs2 and you cannot change them

**Comment by FlamesONE** [comment]
Hello, thank you for ur notice.
I already know about this bug (and others with same reason)
If u will check Flute discord, u should know about coming of new version, so all bugs like this will be fixed in the start of new year.

Sorry for that inconvenience, but I want to make it more better!
